services:
  - type: web
    name: manija-awards-2026-web
    env: node
    region: oregon
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: starter
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: "https://siiykcbhciqisyuuufed.supabase.co"
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: "sb_publishable_wQIYm2tookdty-3mDkOOsg_XjNbRPZQ"
